name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - ${{ secrets.DB_PORT }}
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Run tests
        run: vendor/bin/phpunit tests/Feature/WordControllerTest.php

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install npm dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}

      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: gimyumin40/jitsu
          stage: main
          yaml: |
            name: project-jitsu-deployment-repo
            app: php
            options:
              ports: 9000
              docbase: /public
              nodejs: true
              env:
                - name: APP_KEY
                  value: ${{ secrets.APP_KEY }}
                - name: LOG_CHANNEL
                  value: errorlog
                - name: APP_URL
                  value: ${{ secrets.APP_URL }}
                - name: APP_ENV
                  value: ${{ secrets.APP_ENV }}
                - name: DB_CONNECTION
                  value: ${{ secrets.DB_CONNECTION }}
                - name: DB_HOST
                  value: ${{ secrets.DB_HOST }}
                - name: DB_PORT
                  value: ${{ secrets.DB_PORT }}
                - name: DB_DATABASE
                  value: ${{ secrets.DB_DATABASE }}
                - name: DB_USERNAME
                  value: ${{ secrets.DB_USERNAME }}
                - name: DB_PASSWORD
                  value: ${{ secrets.DB_PASSWORD }}
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
