name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install npm dependencies
        run: npm install

      - name: Build assets
        run: npm run build

      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}

      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: gimyumin40/jitsu
          stage: main
          yaml: |
            name: project-jitsu-deployment-repo
            app: php
            options:
              ports: 9000
              docbase: /public
              nodejs: true
              env:
                - name: APP_KEY
                  value: base64:3msdjscoKayH6sw0w6c/Xwx0wtZcXUoa3RB0JqjmRXY=
                - name: LOG_CHANNEL
                  value: errorlog
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
